"""
XPath's used by the API (*unfinished)

Note: These are not currently implemented
"""

PORT_MAPPING = 'Device/NAT/PortMappings/PortMapping[@uid={uid}]'
PORT_MAPPINGS = 'Device/NAT/PortMappings'
PORT_MAPPING_EXTERNAL_PORT = 'Device/NAT/PortMappings/PortMapping[@uid={uid}]/ExternalPort'
PORT_MAPPING_DESCRIPTION = 'Device/NAT/PortMappings/PortMapping[@uid={uid}]/Description'
PORT_MAPPING_REMOTE_HOST = 'Device/NAT/PortMappings/PortMapping[@uid={uid}]/RemoteHost'
PORT_MAPPING_INTERNAL_CLIENT = 'Device/NAT/PortMappings/PortMapping[@uid={uid}]/InternalClient'
PORT_MAPPING_ALIAS = 'Device/NAT/PortMappings/PortMapping[@uid={uid}]/Alias'
PORT_MAPPING_ENABLE = 'Device/NAT/PortMappings/PortMapping[@uid={uid}]/Enable'
PORT_MAPPING_SERVICE = 'Device/NAT/PortMappings/PortMapping[@uid={uid}]/Service'
PORT_MAPPING_INTERNAL_PORT = 'Device/NAT/PortMappings/PortMapping[@uid={uid}]/InternalPort'
PORT_MAPPING_PROTOCOL = 'Device/NAT/PortMappings/PortMapping[@uid={uid}]/Protocol'
PORT_MAPPING_EXTERNAL_PORT_END_RANGE = 'Device/NAT/PortMappings/PortMapping[@uid={uid}]/ExternalPortEndRange'
PORT_MAPPING_EXTERNAL_INTERFACE = 'Device/NAT/PortMappings/PortMapping[@uid={uid}]/ExternalInterface'
PORT_MAPPING_ALL_EXTERNAL_INTERFACES = 'Device/NAT/PortMappings/PortMapping[@uid={uid}]/AllExternalInterfaces'
PORT_MAPPING_LEASE_DURATION = 'Device/NAT/PortMappings/PortMapping[@uid={uid}]/LeaseDuration'
PORT_MAPPING_INTERNAL_INTERFACE = 'Device/NAT/PortMappings/PortMapping[@uid={uid}]/InternalInterface'
PORT_MAPPING_CREATOR = 'Device/NAT/PortMappings/PortMapping[@uid={uid}]/Creator'
PORT_MAPPING_TARGET = 'Device/NAT/PortMappings/PortMapping[@uid={uid}]/Target'
PORT_MAPPING_LEASE_START = 'Device/NAT/PortMappings/PortMapping[@uid={uid}]/LeaseStart'
#NETMASK_LAN = 'Device/Managers/NetworkData/NetmaskLan'
#TR69_PORT = 'Device/ManagementServer/TR69InternalData/Settings/Port'
#PORT_CLAMPING_ENABLE = 'Device/Services/DeviceConfig/PortClampingEnable'
IP_LAN = 'Device/Managers/NetworkData/IpLan'
#SIP_ALG_ENABLE = 'Device/NAT/SIPALGEnable'
FIREWALL_CONFIG = 'Device/Firewall/Config'
IPV4_ADDRESS = 'Device/IP/Interfaces/Interface[Alias="IP_DATA"]/IPv4Addresses/IPv4Address[Alias="IP_DATA_ADDRESS"]/IPAddress'
HOST_NAME = 'Device/DNS/Client/HostName'
#mainUsbPhysicalMedium='Device/Services/StorageServices/StorageService[@uid=\'1\']/PhysicalMediums/PhysicalMedium[SerialNumber=\'{serial_number}\']'
#mainUsbPhysicalMediumUID='Device/Services/StorageServices/StorageService[@uid=\'1\']/PhysicalMediums/PhysicalMedium[@uid=\'{uid}\']'
#mainWifiLayerInterfaceWifi5='Device/WiFi/Radios/Radio[RADIO5G]'
#mainWifiLayerInterfaceWifi24='Device/WiFi/Radios/Radio[RADIO2G4]'
STORAGE_SERVICE_LOGICAL_VOLUMES = 'Device/Services/StorageServices/StorageService[@uid={uid}]/LogicalVolumes'
STORAGE_SERVICE_LOGICAL_VOLUMES_USB = 'Device/Services/StorageServices/StorageService[@uid=1]/LogicalVolumes'
HOSTS = 'Device/Hosts/Hosts'
HOSTS_HISTORY_MAX_AGE_IN_DAYS = 'Device/Hosts/HistoryMaxAgeInDays'
LOCAL_DOMAINS = 'Device/DNS/Client/LocalDomains'
PRODUCT_CLASS = 'Device/DeviceInfo/ProductClass'
ONLINE_INSTALL_ENABLE = 'Device/Services/OnlineInstall/Enable'
ONLINE_INSTALL_ENABLE_GREYED_OUT = 'Device/Services/OnlineInstall/EnableGreyedOut'
ONLINE_INSTALL_ENGINEER_MODE_TIMEOUT = 'Device/Services/OnlineInstall/EngineerModeTimeout'
#loginClearTextPassword='Device/UserAccounts/Users/User[Login=\'{login}\']/ClearTextPassword'
#loginPassword='Device/UserAccounts/Users/User[Login=\'{login}\']/Password'
PASSWORD_HINT = 'Device/UserAccounts/Users/User[Login="{login}"]/SecretQuery'
GLOBAL_MANAGERS = 'Device/Managers/Global'
#PARENTAL_CONTROL_TIME_SLOTS = 'Device/Services/ParentalControl/TimeSlotLists/TimeSlotList[last()]/TimeSlots'
PARENTAL_CONTROL_MAC_ADDRESS_LISTS = 'Device/Services/ParentalControl/MACAddressLists'
PARENTAL_CONTROL_RULES = 'Device/Services/ParentalControl/Rules'
PARENTAL_CONTROL_TIME_SLOTS = 'Device/Services/ParentalControl/TimeSlotLists/TimeSlotList[@uid=\'{uid}\']/TimeSlots'
#PARENTAL_CONTROL_TIME_SLOTS_BLOCK_ALL_DEVICES = 'Device/Services/ParentalControl/TimeSlotLists/TimeSlotList[Alias=\'BlockAllDevices\']/TimeSlots'
PARENTAL_CONTROL_TIME_SLOT_LISTS = 'Device/Services/ParentalControl/TimeSlotLists'
PARENTAL_CONTROL_ENABLE = 'Device/Services/ParentalControl/Enable'
PARENTAL_CONTROL_MAC_ADDRESS_LIST ='Device/Services/ParentalControl/MACAddressLists/MACAddressList[@uid=\'{uid}\']'
#PARENTAL_CONTROL_MAC_ADDRESS_LIST_BLOCK_ALL_DEVICES = 'Device/Services/ParentalControl/MACAddressLists/MACAddressList[@uid=\'1\']'
PARENTAL_CONTROL = 'Device/Services/ParentalControl'
PARENTAL_CONTROL_RULE = 'Device/Services/ParentalControl/Rules/Rule[@uid=\'{uid}\']'
#btAccessControlUpdateStartTimeBlockAll='Device/Services/ParentalControl/TimeSlotLists/TimeSlotList[Alias=\'BlockAllDevices\']/TimeSlots/TimeSlot[@uid=\'{uid}\']/StartTime'
PARENTAL_CONTROL_TIME_SLOT_START_TIME = 'Device/Services/ParentalControl/TimeSlotLists/TimeSlotList[Alias=\'{alias}\']/TimeSlots/TimeSlot[@uid=\'{uid}\']/StartTime'
PARENTAL_CONTROL_MAC_ADDRESS_LIST_IP_ADDRESS = 'Device/Services/ParentalControl/MACAddressLists/MACAddressList[@uid=\'{uid}\']/IPAddress'
#btAccessControlUpdateBlockAllAlways='Device/Services/ParentalControl/TimeSlotLists/TimeSlotList[Alias=\'BlockAllDevices\']/Always'
PARENTAL_CONTROL_TIME_SLOT_LIST_ALWAYS = 'Device/Services/ParentalControl/TimeSlotLists/TimeSlotList[Alias=\'{alias}\']/Always'
btAccessControlUpdateMacAddress='Device/Services/ParentalControl/MACAddressLists/MACAddressList[@uid=\'{uid}\']/MACAddresses'
btAccessControlUpdateWeekDaysBlockAll='Device/Services/ParentalControl/TimeSlotLists/TimeSlotList[Alias=\'BlockAllDevices\']/TimeSlots/TimeSlot[@uid=\'{uid}\']/WeekDays'
btAccessControlUpdateWanAccess='Device/Services/ParentalControl/Rules/Rule[Alias=\'BlockAllDevices\']/WANAccess'
btAccessControlUpdateBlockAllDevices='Device/Services/ParentalControl/MACAddressLists/MACAddressList/AllDevices'
btAccessControlUpdateWeekDays='Device/Services/ParentalControl/TimeSlotLists/TimeSlotList[@uid=\'{uid}\']/TimeSlots/TimeSlot[@uid=\'{slot_uid}\']/WeekDays'
btAccessControlUpdateEnableBlockAll='Device/Services/ParentalControl/Rules/Rule[Alias=\'BlockAllDevices\']/Enable'
btAccessControlUpdateEnable='Device/Services/ParentalControl/Rules/Rule[@uid=\'{uid}\']/Enable'
btAccessControlUpdateBlockAll='Device/Services/ParentalControl/MACAddressLists/MACAddressList[Alias=\'BlockAllDevices\']/AllDevices'
btAccessControlUpdateEndTimeBlockAll='Device/Services/ParentalControl/TimeSlotLists/TimeSlotList[Alias=\'BlockAllDevices\']/TimeSlots/TimeSlot[@uid=\'{uid}\']/EndTime'
btAccessControlUpdateStartTime='Device/Services/ParentalControl/TimeSlotLists/TimeSlotList[@uid=\'{uid}\']/TimeSlots/TimeSlot[@uid=\'{slot_uid}\']/StartTime'
btAccessControlUpdateEndTime='Device/Services/ParentalControl/TimeSlotLists/TimeSlotList[@uid=\'{uid}\']/TimeSlots/TimeSlot[@uid=\'{slot_uid}\']/EndTime'
btAccessControlTimeSlotChild='Device/Services/ParentalControl/TimeSlotLists/TimeSlotList[@uid=\'{uid}\']/TimeSlots/TimeSlot[@uid=\'{slot_uid}\']'
btAccessControlTimeSlotList='Device/Services/ParentalControl/TimeSlotLists/TimeSlotList[@uid=\'{uid}\']'
btAccessControlRemoveTimeSlotBlockAll='Device/Services/ParentalControl/TimeSlotLists/TimeSlotList[Alias=\'BlockAllDevices\']/TimeSlots/TimeSlot[@uid=\'{uid}\']'
deviceDiscover='Device/DeviceDiscovery/DeviceIdentification/DeviceTypes'
#statsWanStats='Device/IP/Interfaces'
#statsDataUsageDataSent='Device/IP/Interfaces/Interface[Alias="IP_DATA"]/Stats/BytesSent'
#statsDataUsageDataReceived='Device/IP/Interfaces/Interface[Alias="IP_DATA"]/Stats/BytesReceived'
ethernetDeviceDevicesList='Device/Hosts/Hosts/Host[@uid=\'{uid}\']'
#internetConnectivityLastPPPConnectionDsl='Device/PPP/Interfaces/Interface[Alias=\'PPP_DSL_DATA\']/LastPPPConnections'
#internetConnectivityPppFTTHPassword='Device/PPP/Interfaces/Interface[Alias=\'PPP_FTTH_DATA\']/Password'
#internetConnectivityPppFTTHEnable='Device/PPP/Interfaces/Interface[Alias=\'PPP_FTTH_DATA\']/Enable'
#internetConnectivityPppFTTHStatus='Device/PPP/Interfaces/Interface[Alias=\'PPP_FTTH_DATA\']/Status'
#internetConnectivityPppFTTHUsername='Device/PPP/Interfaces/Interface[Alias=\'PPP_FTTH_DATA\']/Username'
#internetConnectivityPppDSLPassword='Device/PPP/Interfaces/Interface[Alias=\'PPP_DSL_DATA\']/Password'
#internetConnectivityPppDSLEnable='Device/PPP/Interfaces/Interface[Alias=\'PPP_DSL_DATA\']/Enable'
#internetConnectivityPppDSLStatus='Device/PPP/Interfaces/Interface[Alias=\'PPP_DSL_DATA\']/Status'
#internetConnectivityPppDSLUsername='Device/PPP/Interfaces/Interface[Alias=\'PPP_DSL_DATA\']/Username'
#internetConnectivityOperatingModeEncapsulation='Device/ATM/Links/Link[Alias=\'ATM_DATA\']/Encapsulation'
#internetConnectivityOperatingModeDestinationAddress='Device/ATM/Links/Link[Alias=\'ATM_DATA\']/DestinationAddress'
#internetConnectivityOperatingModeLinkType='Device/ATM/Links/Link[Alias=\'ATM_DATA\']/LinkType'
#internetConnectivityVpnPortClamping='Device/Services/DeviceConfig/PortClampingEnable'
#internetConnectivityIpv6LinkLocalAddress='Device/IP/Interfaces/Interface[Alias=\'IP_DATA\']/IPv6Addresses/IPv6Address[Alias=\'LINK_LOCAL\']/IPAddress'
#internetConnectivityIpv6StatefullLessAdvManagedFlag='Device/RouterAdvertisement/InterfaceSettings/InterfaceSetting[Alias=\'RA_BR_LAN\']/AdvManagedFlag'
#internetConnectivityIpv6StatefullLess='Device/DHCPv6/Server/Pools/Pool[Alias=\'DEFAULT_POOL\']/IANAEnable'
#internetConnectivityIpv6FtthInterface='Device/PPP/Interfaces/Interface[Alias=\'PPP_FTTH_DATA\']/Status'
#internetConnectivityIpv6FtthRemoteLocal='Device/PPP/Interfaces/Interface[Alias=\'PPP_FTTH_DATA\']/IPv6CP/RemoteInterfaceIdentifier'
#internetConnectivityIpv6NetworkStatus='Device/DHCPv6/Server/Pools/Pool[Alias=\'DEFAULT_POOL\']/Status'
#internetConnectivityIpv6UlaEnablePrefix='Device/IP/Interfaces/Interface[Alias=\'IP_BR_LAN\']/IPv6Prefixes/IPv6Prefix[Alias=\'ULA_LAN\']/Enable'
#internetConnectivityIpv6UlaPrefix='Device/IP/Interfaces/Interface[Alias=\'IP_BR_LAN\']/IPv6Prefixes/IPv6Prefix[Alias=\'ULA_LAN\']/Prefix'
#internetConnectivityIpv6LinkLocalAddressLAN='Device/IP/Interfaces/Interface[Alias=\'IP_BR_LAN\']/IPv6Addresses/IPv6Address[Alias=\'LINK_LOCAL\']/IPAddress'
#internetConnectivityIpv6DhcpMode='Device/Managers/NetworkData/IPv6Mode'
#internetConnectivityIpv6DslRemoteLocal='Device/PPP/Interfaces/Interface[Alias=\'PPP_DSL_DATA\']/IPv6CP/RemoteInterfaceIdentifier'
#internetConnectivityIpv6PreferedIPDATAAddr='Device/IP/Interfaces/Interface[Alias=\'IP_DATA\']/IPv6Addresses/IPv6Address[IPAddressStatus=\'PREFERRED\']'
internetConnectivityIpv6PreferedIPBRLANAddr='Device/IP/Interfaces/Interface[Alias=\'IP_BR_LAN\']/IPv6Addresses/IPv6Address[IPAddressStatus=\'PREFERRED\']'
internetConnectivityIpv6LocalDomains='Device/DNS/Relay/LocalDomains'
#internetConnectivityIpv6HubStatus='Device/IP/IPv6Status'
internetConnectivityIpv6StatefullLessAdvOtherConfigFlag='Device/RouterAdvertisement/InterfaceSettings/InterfaceSetting[Alias=\'RA_BR_LAN\']/AdvOtherConfigFlag'
internetConnectivityIpv6Hostname='Device/DNS/Client/HostName'
internetConnectivityIpv6UlaEnableAddress='Device/IP/Interfaces/Interface[Alias=\'IP_BR_LAN\']/IPv6Addresses/IPv6Address[Alias=\'ULA_LAN\']/Enable'
internetConnectivityIpv6DslInterface='Device/PPP/Interfaces/Interface[Alias=\'PPP_DSL_DATA\']/Status'
internetConnectivityIpv6PreferedIPBRLANPrefix='Device/IP/Interfaces/Interface[Alias=\'IP_BR_LAN\']/IPv6Prefixes'
internetConnectivityIpv6UlaAddress='Device/IP/Interfaces/Interface[Alias=\'IP_BR_LAN\']/IPv6Addresses/IPv6Address[Alias=\'ULA_LAN\']/IPAddress'
internetConnectivityIpv6PreferedIPDATAPrefix='Device/IP/Interfaces/Interface[Alias=\'IP_DATA\']/IPv6Prefixes'
internetConnectivityIpv6DnsV6='Device/DNS/Relay/Forwardings/Forwarding[Status=\'ENABLED\']/DNSServer'
internetConnectivityLastPPPConnectionFtth='Device/PPP/Interfaces/Interface[Alias=\'PPP_FTTH_DATA\']/LastPPPConnections'
internetConnectivityLastDSLSynchronization='Device/DSL/Lines/Line[@uid=\'1\']/LastDSLSynchronizations'
eventLog='Device/DeviceInfo/VendorLogFiles/VendorLogFile[@uid=\'1\']'
mySagemcomBoxDynDNSPassword='Device/Services/DynamicDNS/Clients/Client[@uid=\'1\']/Password'
mySagemcomBoxDynDNSHostname='Device/Services/DynamicDNS/Clients/Client[@uid=\'1\']/Hostnames/Hostname[@uid=\'1\']/Name'
mySagemcomBoxDynDNSServiceQuery='Device/Services/DynamicDNS/Services/Service[Name=\'{name}\']'
mySagemcomBoxDynDNSServiceReference='Device/Services/DynamicDNS/Clients/Client[@uid=\'1\']/ServiceReference'
mySagemcomBoxDynDNSEnable='Device/Services/DynamicDNS/Clients/Client[@uid=\'1\']/Enable'
mySagemcomBoxDynDNSServiceQueryIndex='Device/Services/DynamicDNS/Services/Service[@uid=\'{uid}\']'
mySagemcomBoxDynDNSClient='Device/Services/DynamicDNS/Clients/Client[@uid=\'1\']'
mySagemcomBoxDynDNSServices='Device/Services/DynamicDNS/Services'
mySagemcomBoxDynDNSStatus='Device/Services/DynamicDNS/Clients/Client[@uid=\'1\']/Status'
mySagemcomBoxDynDNSUsername='Device/Services/DynamicDNS/Clients/Client[@uid=\'1\']/Username'
mySagemcomBoxBasicStatusDownstreamSyncSpeedDsl='Device/DSL/Channels/Channel[@uid=\'1\']/DownstreamCurrRate'
mySagemcomBoxBasicStatusAccessControl='Device/Hosts/Hosts/Host/BlacklistedSchedule'
mySagemcomBoxBasicStatusFirmwareUpdated='Device/DeviceInfo/BuildDate'
mySagemcomBoxBasicStatusFrontLedColor='Device/Managers/HubLightControl/FrontLEDColor'
mySagemcomBoxBasicStatusDataUsageSent='Device/IP/Interfaces/Interface[Alias=\'IP_DATA\']/Stats/BytesSent'
mySagemcomBoxBasicStatusDataUsageReceived='Device/IP/Interfaces/Interface[Alias=\'IP_DATA\']/Stats/BytesReceived'
mySagemcomBoxBasicStatusNetworkUptime='Device/IP/Interfaces/Interface[Alias=\'IP_DATA\']/LastChange'
mySagemcomBoxBasicStatusUpstreamSyncSpeedDsl='Device/DSL/Channels/Channel[@uid=\'1\']/UpstreamCurrRate'
mySagemcomBoxBasicStatusFirmwareVersion='Device/DeviceInfo/ExternalFirmwareVersion'
mySagemcomBoxUpnpUpnpStatus='Device/UPnP/Device/UPnPIGD'
mySagemcomBoxUpnpUpnpSecurityStatus='Device/UPnP/Settings/ExtendedUPnPSecurity'
mySagemcomBoxMaintenanceSaveRestoreRestore='Device/DeviceInfo/VendorConfigFiles/VendorConfigFile[Alias=\'DEVICE_CONFIG\']'
mySagemcomBoxMaintenanceSaveRestoreSave='Device/DeviceInfo/VendorConfigFiles/VendorConfigFile[Alias=\'DEVICE_CONFIG\']'
mySagemcomBoxMaintenanceNtpLocalTime='Device/Time/CurrentLocalTime'
mySagemcomBoxMaintenanceFirmwareVersion='Device/DeviceInfo/ExternalFirmwareVersion'
mySagemcomBoxDeviceInfoWifiPasswordForbiddenWords='Device/Services/DeviceConfig/WifiPasswordForbiddenWords'
mySagemcomBoxDeviceInfoHubLightBrightness='Device/Managers/HubLightControl/Brightness'
mySagemcomBoxDeviceInfoDatapumpVersion='Device/DSL/Lines/Line[Alias=\'DSL0\']/FirmwareVersion'
mySagemcomBoxDeviceInfoHubLightSchedule='Device/Managers/HubLightControl/Schedule/Enable'
mySagemcomBoxDeviceInfoWanMacAddress='Device/DeviceInfo/MACAddress'
mySagemcomBoxDeviceInfoIPBRLANIpv6='Device/IP/Interfaces/Interface[Alias=\'IP_BR_LAN\']/IPv6Addresses/IPv6Address/IPAddress'
mySagemcomBoxDeviceInfoInterfaceType='Device/Services/DeviceConfig/LastSuccesfulWanType'
mySagemcomBoxDeviceInfoPublicIpv4='Device/IP/Interfaces/Interface[Alias=\'IP_DATA\']/IPv4Addresses/IPv4Address[Alias=\'IP_DATA_ADDRESS\']/IPAddress'
mySagemcomBoxDeviceInfoLocalIpv4='Device/Managers/NetworkData/IpLan'
mySagemcomBoxDeviceInfoLocalEthernetMac='Device/Ethernet/Interfaces/Interface[Alias=\'PHY1\']/MACAddress'
mySagemcomBoxDeviceInfoHardwareVersion='Device/DeviceInfo/HardwareVersion'
mySagemcomBoxDeviceInfoPublicSubnetMask='Device/IP/Interfaces/Interface[Alias=\'IP_DATA\']/IPv4Addresses/IPv4Address[Alias=\'IP_DATA_ADDRESS\']/SubnetMask'
mySagemcomBoxDeviceInfoWifi24UpTime='Device/WiFi/SSIDs/SSID[Alias=\'WL_PRIV2G\']/ConnectionTime'
mySagemcomBoxDeviceInfoWifi24MacAddress='Device/WiFi/SSIDs/SSID[Alias=\'WL_PRIV2G\']/MACAddress'
mySagemcomBoxDeviceInfoWifi24='Device/WiFi/Radios/Radio[Alias=\'RADIO2G4\']'
mySagemcomBoxDeviceInfoWifi24OperatingMode='Device/WiFi/Radios/Radio[Alias=\'RADIO2G4\']/OperatingStandards'
mySagemcomBoxDeviceInfoWifi24MaxBitRate='Device/WiFi/Radios/Radio[Alias=\'RADIO2G4\']/MaxBitRate'
mySagemcomBoxDeviceInfoWifi24ChannelBandwidth='Device/WiFi/Radios/Radio[Alias=\'RADIO2G4\']/OperatingChannelBandwidth'
mySagemcomBoxDeviceInfoWifi24SecurityMode='Device/WiFi/AccessPoints/AccessPoint[Alias=\'PRIV0\']/Security/ModeEnabled'
mySagemcomBoxDeviceInfoWifi24Ssid='Device/WiFi/SSIDs/SSID[Alias=\'WL_PRIV2G\']/SSID'
mySagemcomBoxDeviceInfoWifi24Status='Device/WiFi/SSIDs/SSID[Alias=\'WL_PRIV2G\']/Status'
mySagemcomBoxDeviceInfoProductClass='Device/DeviceInfo/ProductClass'
mySagemcomBoxDeviceInfoSerialNumber='Device/DeviceInfo/SerialNumber'
mySagemcomBoxDeviceInfoWanInternetStatus='Device/IP/Interfaces/Interface[Alias=\'IP_DATA\']/Status'
mySagemcomBoxDeviceInfoWanWanStatus='Device/PPP/Interfaces/Interface[Alias=\'PPP_FTTH_DATA\']/Status'
mySagemcomBoxDeviceInfoWanFtthLowerLayer='Device/Ethernet/Links/Link[Alias=\'FTTH_DATA\']/LowerLayers'
mySagemcomBoxDeviceInfoWanRealConnectionStatus='Device/PPP/Interfaces/Interface[Alias=\'PPP_FTTH_DATA\']/ConnectionStatus'
mySagemcomBoxDeviceInfoWanConnectionStatusPhy4='Device/Ethernet/Interfaces/Interface[Alias=\'PHY4\']/Status'
mySagemcomBoxDeviceInfoWanConnectionStatusPhy6='Device/Ethernet/Interfaces/Interface[Alias=\'PHY6_WAN\']/Status'
mySagemcomBoxDeviceInfoDNS='Device/IP/Interfaces/Interface[Alias=\'IP_DATA\']/IPv4Addresses/IPv4Address[Alias=\'IP_DATA_ADDRESS\']/Dns'
mySagemcomBoxDeviceInfoLinkLocalIpv6='Device/IP/Interfaces/Interface[Alias=\'IP_BR_LAN\']/IPv6Addresses/IPv6Address[Alias=\'LINK_LOCAL\']/IPAddress'
mySagemcomBoxDeviceInfoDefaultGateway='Device/IP/Interfaces/Interface[Alias=\'IP_DATA\']/IPv4Addresses/IPv4Address/IPGateway'
mySagemcomBoxDeviceInfoUpTime='Device/DeviceInfo/UpTime'
mySagemcomBoxDeviceInfoHubLightStatus='Device/Managers/HubLightControl/LedEnable'
mySagemcomBoxDeviceInfoLocalSubnetMask='Device/Managers/NetworkData/NetmaskLan'
mySagemcomBoxDeviceInfoXdslRealConnectionStatus='Device/PPP/Interfaces/Interface[Alias=\'PPP_DSL_DATA\']/ConnectionStatus'
mySagemcomBoxDeviceInfoXdslConnectionStatus='Device/DSL/Lines/Line[Alias=\'DSL0\']/Status'
mySagemcomBoxDeviceInfoXdslNumericActualRateUp='Device/DSL/Channels/Channel[@uid=\'1\']/UpstreamCurrRate'
mySagemcomBoxDeviceInfoXdslNumericActualRateDown='Device/DSL/Channels/Channel[@uid=\'1\']/DownstreamCurrRate'
mySagemcomBoxDeviceInfoXdslConnectionTimeDsl='Device/DSL/Lines/Line[@uid=\'1\']/LastChange'
mySagemcomBoxDeviceInfoSoftwareVersion='Device/DeviceInfo/ExternalFirmwareVersion'
mySagemcomBoxDeviceInfoWifi5UpTime='Device/WiFi/SSIDs/SSID[Alias=\'WL_PRIV5G\']/ConnectionTime'
mySagemcomBoxDeviceInfoWifi5MacAddress='Device/WiFi/SSIDs/SSID[Alias=\'WL_PRIV5G\']/MACAddress'
mySagemcomBoxDeviceInfoWifi5O='Device/WiFi/Radios/Radio[Alias=\'RADIO5G\']'
mySagemcomBoxDeviceInfoWifi5OperatingMode='Device/WiFi/Radios/Radio[Alias=\'RADIO5G\']/OperatingStandards'
mySagemcomBoxDeviceInfoWifi5MaxBitRate='Device/WiFi/Radios/Radio[Alias=\'RADIO5G\']/MaxBitRate'
mySagemcomBoxDeviceInfoWifi5ChannelBandwidth='Device/WiFi/Radios/Radio[Alias=\'RADIO5G\']/OperatingChannelBandwidth'
mySagemcomBoxDeviceInfoWifi5SecurityMode='Device/WiFi/AccessPoints/AccessPoint[Alias=\'PRIV1\']/Security/ModeEnabled'
mySagemcomBoxDeviceInfoWifi5Ssid='Device/WiFi/SSIDs/SSID[Alias=\'WL_PRIV5G\']/SSID'
mySagemcomBoxDeviceInfoWifi5Status='Device/WiFi/SSIDs/SSID[Alias=\'WL_PRIV5G\']/Status'
mySagemcomBoxDhcpSubnetMaskDefault='Device/Managers/NetworkData/NetmaskLan'
mySagemcomBoxDhcpIpv4Address2='Device/DHCPv4/Server/Pools/Pool[Alias=\'DEFAULT_POOL\']/IPInterface'
mySagemcomBoxDhcpIpv4PoolEnd2='Device/DHCPv4/Server/Pools/Pool[Alias=\'DEFAULT_POOL\']/MaxAddress'
mySagemcomBoxDhcpIpv4PoolStart2='Device/DHCPv4/Server/Pools/Pool[Alias=\'DEFAULT_POOL\']/MinAddress'
mySagemcomBoxDhcpIpv4Address='Device/Managers/NetworkData/IpLan'
mySagemcomBoxDhcpSubnetMask='Device/Managers/NetworkData/NetmaskLan'
mySagemcomBoxDhcpDhcpAuthoritative='Device/DHCPv4/Server/X_SAGEMCOM_Authoritative'
mySagemcomBoxDhcpEnable='Device/DHCPv4/Server/Enable'
mySagemcomBoxDhcpIpv4PoolStart='Device/Managers/NetworkData/DhcpLanMinAddress'
mySagemcomBoxDhcpHost='Device/DNS/Client/HostName'
mySagemcomBoxDhcpDhcpv4LeaseTime='Device/DHCPv4/Server/Pools/Pool[Alias=\'DEFAULT_POOL\']/LeaseTime'
mySagemcomBoxDhcpIPReservation='Device/DHCPv4/Server/Pools/Pool[Alias=\'DEFAULT_POOL\']/StaticAddresses'
mySagemcomBoxDhcpSubnetMask2='Device/DHCPv4/Server/Pools/Pool[Alias=\'DEFAULT_POOL\']/SubnetMask'
mySagemcomBoxDhcpIpv4PoolEnd='Device/Managers/NetworkData/DhcpLanMaxAddress'
adminAdvancedConnectionUptime='Device/IP/Interfaces/Interface[Alias=\'IP_DATA\']/LastChange'
wifiMacfilterWifiControlList='Device/WiFi/AccessPoints/AccessPoint[Alias=\'{ap}\']/MACFiltering/MACAddresses'
wifiMacfilterMacFilterMode='Device/WiFi/AccessPoints/AccessPoint[Alias=\'{ap}\']/MACFiltering/Mode'
wifiGeneralBroadcast='Device/WiFi/AccessPoints/AccessPoint[Alias=\'{ap}\']/SSIDAdvertisementEnabled'
wifiGeneralWpsEnable='Device/WiFi/AccessPoints/AccessPoint[Alias=\'{ap}\']/WPS/Enable'
wifiGeneralChannel='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/Channel'
wifiGeneralSecurityModesSupported='Device/WiFi/AccessPoints/AccessPoint[Alias=\'{ap}\']/Security/ModesSupported'
wifiGeneralSecurityMode='Device/WiFi/AccessPoints/AccessPoint[Alias=\'{ap}\']/Security/ModeEnabled'
wifiGeneralPasswordWep='Device/WiFi/AccessPoints/AccessPoint[Alias=\'{ap}\']/Security/WEPKey'
wifiGeneralSsid='Device/WiFi/SSIDs/SSID[Alias=\'{ssid}\']/SSID'
wifiGeneralMac='Device/WiFi/SSIDs/SSID[Alias=\'{ssid}\']/MACAddress'
wifiGeneralPasswordKey='Device/WiFi/AccessPoints/AccessPoint[Alias=\'{ap}\']/Security/KeyPassphrase'
wifiGeneralChannelsInUse='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/ChannelsInUse'
wifiGeneralAutoChannel='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/AutoChannelEnable'
wifiGeneralPossibleChannels='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/PossibleChannels'
wifiGeneralEnable='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/Enable'
wifiGeneralOperatingStandards='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/OperatingStandards'
wifiGeneralChannelBandwidth='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/OperatingChannelBandwidth'
wifiGeneralPossibleSecurityMode='Device/WiFi/AccessPoints/AccessPoint[Alias=\'{ap}\']/Security/ModesSupported'
wifiGeneralAutoChannelTrigger='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/AutoChannelTrigger'
wifiGeneralWirelessVisible='Device/WiFi/AccessPoints/AccessPoint[Alias=\'{ap}\']/Enable'
wifiGeneralExtensionChannel='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/ExtensionChannel'
wifiGeneralSsidEnable='Device/WiFi/SSIDs/SSID[Alias=\'{ssid}\']/Enable'
wifiGeneralTransmitPower='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/TransmitPower'
wifiRPCWpsRPC='Device/WiFi/AccessPoints/AccessPoint[Alias=\'{ap}\']'
wifiStatsMaxBitRate='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/MaxBitRate'
wifiStatsStatus='Device/WiFi/SSIDs/SSID[Alias=\'{ssid}\']/Status'
wifiAdvancedGlobalMaxClients='Device/WiFi/AccessPoints/AccessPoint[Alias=\'{ap}\']/MaxAssociatedDevices'
wifiAdvancedBandSteering='Device/WiFi/BandSteering/Enable'
wifiAdvancedOperatingStandards='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/OperatingStandards'
wifiAdvancedChannelBandwidth='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/OperatingChannelBandwidth'
wifiAdvancedWmmEnable='Device/WiFi/AccessPoints/AccessPoint[Alias=\'{ap}\']/WMMEnable'
wifiAdvancedExtensionChannel='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/ExtensionChannel'
wifiAdvancedApsd='Device/WiFi/AccessPoints/AccessPoint[Alias=\'{ap}\']/UAPSDEnable'
wifiAdvancedRegulatoryDomain='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/RegulatoryDomain'
wifiAdvancedTransmitPower='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/TransmitPower'
wifiMainPageMode='Device/WiFi/AccessPoints/AccessPoint[Alias=\'{ap}\']/Security/ModeEnabled'
wifiMainPageOperatingMode='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/OperatingStandards'
wifiMainPageMaxBitRate='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/MaxBitRate'
wifiMainPageChannelBandwidth='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/OperatingChannelBandwidth'
wifiMainPageAssociatedDevices='Device/WiFi/AccessPoints/AccessPoint[Alias=\'{ap}\']/AssociatedDevices'
wifiMainPageSsid='Device/WiFi/SSIDs/SSID[Alias=\'{ssid}\']'
wifiIndexOperatingMode='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/OperatingStandards'
wifiIndexWpsEnable='Device/WiFi/AccessPoints/AccessPoint[Alias=\'{ap}\']/WPS/Enable'
wifiIndexChannel='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/Channel'
wifiIndexSecurityMode='Device/WiFi/AccessPoints/AccessPoint[Alias=\'{ap}\']/Security/ModeEnabled'
wifiIndexSsid='Device/WiFi/SSIDs/SSID[Alias=\'{ssid}\']/SSID'
wifiIndexUpTime='Device/WiFi/SSIDs/SSID[Alias=\'{ssid}\']/ConnectionTime'
wifiIndexMacAddress='Device/WiFi/SSIDs/SSID[Alias=\'{ssid}\']/MACAddress'
wifiIndexPassword='Device/WiFi/AccessPoints/AccessPoint[Alias=\'{ap}\']/Security/KeyPassphrase'
wifiIndexAutoChannel='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/AutoChannelEnable'
wifiIndexEnable='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/Enable'
wifiIndexMaxBitRate='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/MaxBitRate'
wifiIndexChannelBandwidth='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/OperatingChannelBandwidth'
wifiIndexWirelessVisible='Device/WiFi/AccessPoints/AccessPoint[Alias=\'{ap}\']/Enable'
wifiIndexStatus='Device/WiFi/SSIDs/SSID[Alias=\'{ssid}\']/Status'
wifiRecommendedChannelTestChannel='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/SiteSurvey/ChannelsToTest'
wifiRecommendedChannelSubscribe='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/SiteSurvey/State'
wifiRecommendedChannelSurvey='Device/WiFi/Radios/Radio[Alias=\'{radio}\']/SiteSurvey/ChannelSurveys'
wifiRedsideAliases='Device/WiFi/SSIDs/SSID/Alias'
wifiGeneralCommonWifiAutoChannelTrigger='Device/WiFi/Radios/Radio/AutoChannelTrigger'
wifiGeneralCommonWifiMode='Device/Services/DeviceConfig/WiFiMode'
domainLockList='Device/Services/DeviceConfig/DomainLockList'
domainLockEnable='Device/Services/DeviceConfig/DomainLockingEnable'
deviceNATPortMappingsDMZInternalClient='Device/NAT/PortMappings/PortMapping[Service=\'DMZ\']/InternalClient'
deviceNATPortMappingsDMZEnable='Device/NAT/PortMappings/PortMapping[Service=\'DMZ\']/Enable'
deviceNATPortMappingsNotDMZ='Device/NAT/PortMappings/PortMapping[Alias!=\'API_DMZ\']'
pinholesSaveMacID='Device/Firewall/Chains/Chain[Name=\'Low\']/Rules/Rule[@uid=\'{uid}\']/MacId'
pinholesSaveDescription='Device/Firewall/Chains/Chain[Name=\'Low\']/Rules/Rule[@uid=\'{uid}\']/Description'
pinholesSaveDestIP='Device/Firewall/Chains/Chain[Name=\'Low\']/Rules/Rule[@uid=\'{uid}\']/DestIP'
pinholesSaveDestPort='Device/Firewall/Chains/Chain[Name=\'Low\']/Rules/Rule[@uid=\'{uid}\']/DestPort'
pinholesSaveSourcePortRangeMax='Device/Firewall/Chains/Chain[Name=\'Low\']/Rules/Rule[@uid=\'{uid}\']/SourcePortRangeMax'
pinholesSaveDestPortRangeMax='Device/Firewall/Chains/Chain[Name=\'Low\']/Rules/Rule[@uid=\'{uid}\']/DestPortRangeMax'
pinholesSaveList='Device/Firewall/Chains/Chain[Name=\'Low\']/Rules'
pinholesSaveProtocol='Device/Firewall/Chains/Chain[Name=\'Low\']/Rules/Rule[@uid=\'{uid}\']/Protocol'
pinholesSaveSourcePort='Device/Firewall/Chains/Chain[Name=\'Low\']/Rules/Rule[@uid=\'{uid}\']/SourcePort'
pinholesSaveRemove='Device/Firewall/Chains/Chain[Name=\'Low\']/Rules/Rule[@uid=\'{uid}\']'
pinholesRule='Device/Firewall/Chains/Chain[Name=\'Low\']/Rules/Rule[@uid=\'{uid}\']'
pinholesList='Device/Firewall/Chains/Chain[Name=\'Low\']/Rules/Rule[IPVersion=\'6\']'
firstConnection='Device/DeviceInfo/FirstConnection'
technicalLogDataSent='Device/IP/Interfaces/Interface[Alias=\'IP_DATA\']/Stats/BytesSent'
technicalLogBtWifi='Device/Services/OpenWiFi/OpenWifiOptedIn'
technicalLogInterleaveDelayUs='Device/DSL/Channels/Channel[Alias=\'DSL0\']/ActualInterleavingDelayus'
technicalLogModulation='Device/DSL/Lines/Line[Alias=\'DSL0\']/StandardUsed'
technicalLogBoardVersion='Device/DeviceInfo/HardwareVersion'
technicalLogMaximumDataRateDown='Device/DSL/Lines/Line[Alias=\'DSL0\']/DownstreamMaxBitRate'
technicalLogDataReceived='Device/IP/Interfaces/Interface[Alias=\'IP_DATA\']/Stats/BytesReceived'
technicalLogWifiMode='Device/Services/DeviceConfig/WiFiMode'
technicalLogProductName='Device/DeviceInfo/ModelName'
technicalLogFirmwareUpdated='Device/DeviceInfo/BuildDate'
technicalLogSignalAttenuationDown='Device/DSL/Lines/Line[Alias=\'DSL0\']/SignalDownstreamAttenuation'
technicalLogMaximumDataRateUp='Device/DSL/Lines/Line[Alias=\'DSL0\']/UpstreamMaxBitRate'
technicalLogWifiSecurity='Device/WiFi/AccessPoints/AccessPoint[Alias=\'PRIV0\']/Security/ModeEnabled'
technicalLogNoiseMarginUp='Device/DSL/Lines/Line[Alias=\'DSL0\']/UpstreamNoiseMargin'
technicalLogVpiVci='Device/ATM/Links/Link[Alias=\'ATM_DATA\']/DestinationAddress'
technicalLogFirmwareVersion='Device/DeviceInfo/ExternalFirmwareVersion'
technicalLogFtthStatus='Device/PPP/Interfaces/Interface[Alias=\'PPP_FTTH_DATA\']/Status'
technicalLogBootLoader='Device/DeviceInfo/BootloaderVersion'
technicalLogBroadbandUsernameFTTH='Device/PPP/Interfaces/Interface[Alias=\'PPP_FTTH_DATA\']/Username'
technicalLogSerialNumber='Device/DeviceInfo/SerialNumber'
technicalLogWifiSSID24='Device/WiFi/SSIDs/SSID[Alias=\'WL_PRIV2G\']/SSID'
technicalLogBandSteering='Device/WiFi/BandSteering/Enable'
technicalLogInterleaveDelay='Device/DSL/Channels/Channel[Alias=\'DSL0\']/ActualInterleavingDelay'
technicalLogWifiChannel24='Device/WiFi/Radios/Radio[Alias=\'RADIO2G4\']/Channel'
technicalLogLineAttenuation='Device/DSL/Lines/Line[Alias=\'DSL0\']/DownstreamAttenuation'
technicalLogNoiseMarginDown='Device/DSL/Lines/Line[Alias=\'DSL0\']/DownstreamNoiseMargin'
technicalLogWifiSmart5='Device/WiFi/Radios/Radio[Alias=\'RADIO5G\']/AutoChannelEnable'
technicalLogBroadbandUsernameDSL='Device/PPP/Interfaces/Interface[Alias=\'PPP_DSL_DATA\']/Username'
technicalLogDataRateDown='Device/DSL/Channels/Channel[Alias=\'DSL0\']/DownstreamCurrRate'
technicalLogSignalAttenuationUp='Device/DSL/Lines/Line[Alias=\'DSL0\']/SignalUpstreamAttenuation'
technicalLogWifiSSID5='Device/WiFi/SSIDs/SSID[Alias=\'WL_PRIV5G\']/SSID'
technicalLogMacAddress='Device/DeviceInfo/MACAddress'
technicalLogWifiChannel5='Device/WiFi/Radios/Radio[Alias=\'RADIO5G\']/Channel'
technicalLogDslUptime='Device/DSL/Lines/Line[Alias=\'DSL0\']/LastChange'
technicalLogFirewall='Device/Firewall/Enable'
technicalLogWifiSmart24='Device/WiFi/Radios/Radio[Alias=\'RADIO2G4\']/AutoChannelEnable'
technicalLogDataRateUp='Device/DSL/Channels/Channel[Alias=\'DSL0\']/UpstreamCurrRate'
technicalLogDslStatus='Device/PPP/Interfaces/Interface[Alias=\'PPP_DSL_DATA\']/Status'
managementTr69InternalDataPort='Device/ManagementServer/TR69InternalData/Settings/Port'
managementLanguage='Device/UserInterface/CurrentLanguage'
fingerPrintDatabaseEntry='Device/Services/OnlineInstall/DHCPFingerprintDatabase/Entries'
hurlProductVariant='Device/DeviceInfo/ProductVariant'
hurlEnable='Device/Services/DeviceConfig/ConnectionHURLPageEnable'
hubLightControlTurnLightOn='Device/Managers/HubLightControl/Schedule/TurnLightOn'
hubLightControlTurnLightOff='Device/Managers/HubLightControl/Schedule/TurnLightOff'
hubLightControlLedStatus='Device/Managers/HubLightControl/LedEnable'
hubLightControlScheduleEnable='Device/Managers/HubLightControl/Schedule/Enable'
hubLightControlBrightness='Device/Managers/HubLightControl/Brightness'
forbiddenIpsIpsQuantennaBootIPLocal='Device/WiFi/Quantenna/BootIPLocal'
forbiddenIpsIpsPppFtthDataRemoteIP='Device/PPP/Interfaces/Interface[Alias=\'PPP_FTTH_DATA\']/IPCP/RemoteIPAddress'
forbiddenIpsIpsDataModels='Device/DeviceInfo/SupportedDataModels/SupportedDataModel/URL'
forbiddenIpsIpsQuantennaMngtIPRemote='Device/WiFi/Quantenna/MngtIPRemote'
forbiddenIpsIpsOpenWifiIPInterface='Device/IP/Interfaces/Interface[Alias=\'IP_BR_OPENWIFI\']/IPv4Addresses/IPv4Address[Alias=\'IP_BR_OPENWIFI_ADDRESS\']/IPAddress'
forbiddenIpsIpsQuantennaMngtIPLocal='Device/WiFi/Quantenna/MngtIPLocal'
forbiddenIpsIpsOpenWifiMinAddress='Device/DHCPv4/Server/Pools/Pool[Alias=\'OPENWIFI_POOL\']/MinAddress'
forbiddenIpsIpsOpenWifiMaxAddress='Device/DHCPv4/Server/Pools/Pool[Alias=\'OPENWIFI_POOL\']/MaxAddress'
forbiddenIpsIpsOpenWifiSubnetMask='Device/DHCPv4/Server/Pools/Pool[Alias=\'OPENWIFI_POOL\']/SubnetMask'
forbiddenIpsIpsPppDslDataLocalIP='Device/PPP/Interfaces/Interface[Alias=\'PPP_DSL_DATA\']/IPCP/LocalIPAddress'
forbiddenIpsIpsOpenWifiInterface='Device/DHCPv4/Server/Pools/Pool[Alias=\'OPENWIFI_POOL\']/IPInterface'
forbiddenIpsIpsOpenWifiIPSubnet='Device/IP/Interfaces/Interface[Alias=\'IP_BR_OPENWIFI\']/IPv4Addresses/IPv4Address[Alias=\'IP_BR_OPENWIFI_ADDRESS\']/SubnetMask'
forbiddenIpsIpsPppDslDataRemoteIP='Device/PPP/Interfaces/Interface[Alias=\'PPP_DSL_DATA\']/IPCP/RemoteIPAddress'
forbiddenIpsIpsPppFtthDataLocalIP='Device/PPP/Interfaces/Interface[Alias=\'PPP_FTTH_DATA\']/IPCP/LocalIPAddress'
forbiddenIpsIpsQuantennaBootIPRemote='Device/WiFi/Quantenna/BootIPRemote'
gatewayConnectionStatusLocalipnetworkIpv4address='Device/Managers/NetworkData/IpLan'
gatewayConnectionStatusLocalipnetworkSubnetmask='Device/Managers/NetworkData/NetmaskLan'
device='Device'
bandwidthMonitoring='Device/Services/BandwidthMonitoring'
deviceFastLinesLineTestParamsDownstreamCurrRate='Device/FAST/Lines/Line[@uid=\'1\']/TestParams/DownstreamCurrRate'
deviceFastLinesLineTestParamsUpstreamCurrRate='Device/FAST/Lines/Line[@uid=\'1\']/TestParams/UpstreamCurrRate'
